language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache/files

matrix:
  include:
    - php: 7.0
    - php: 7.1
    - php: 7.2
      env: COVERAGE=1
    - php: 7.3
    - php: hhvm
  allow_failures:
    - php: hhvm
    - php: 7.3
  fast_finish: true

before_install:
  - if [[ $TRAVIS_PHP_VERSION != hhvm && $COVERAGE != 1 ]]; then phpenv config-rm xdebug.ini; fi;
  - composer self-update

install: composer install --prefer-dist --no-interaction

script:
- >
  if [[ "$COVERAGE" != "1" ]]; then
    echo;
    echo "Running unit tests";
    ./bin/phpunit --colors tests/Unit/
  fi
